---
- name: generate variables for deployment
  hosts: localhost
  gather_facts: true
  connection: local
  become: true
  vars:
    - file_source: "network-gateway.yaml"
  vars_files: 
    - ./deployment_vars.yml
    - /ansible/deployment_vars.yml
  roles:
    - generate/host_vm_address #Required for deployment DO NOT REMOVE
    - generate/tftp_server #Required for deployment DO NOT REMOVE
    - generate/dhcp_server #Required for deployment DO NOT REMOVE
    - generate/network_configs #Required for deployment DO NOT REMOVE
    - generate/seconion_iso  #SecurityOnion ManagerSearch

- name: install system and virtual machines
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles: 
    - vmware/esxi/hard_install   #Required for deployment DO NOT REMOVE
    - vmware/vcenter/deploy_vcenter  #Required for deployment DO NOT REMOVE
    - vmware/vcenter/add_esxi_hosts #Required for deployment DO NOT REMOVE
    - vmware/vcenter/configure_vswitch #Required for deployment DO NOT REMOVE
    - PA/create_vm #Required for deployment DO NOT REMOVE
    - splunk/create_splunk_vms #Splunk
    - seconion/upload_iso  #SecurityOnion
    - seconion/deploy_manager_vm  #SecurityOnion
    - vmware/vcenter/change_centos_vm_address #Splunk

- name: configure Palo Alto
  hosts: PA
  gather_facts: no
  connection: local
  ignore_errors: True
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles: 
    - PA/upload_config #Required for deployment DO NOT REMOVE
    - PA/change_password #Required for deployment DO NOT REMOVE

- name: Change System address
  hosts: localhost
  gather_facts: no
  become: yes
  vars:
    - file_source: "network-eight.yaml"
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles: 
    - generate/host_vm_address #Required for deployment DO NOT REMOVE

- name: Configure Splunk Virtual machines
  hosts: Splunk
  vars:
    - rpm: "{{splunk_file}}"
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles:
    - splunk/create_user #Splunk all
    - splunk/create_dir #Splunk all
    - splunk/partition_drive #Splunk all
    - splunk/selinux_permissive #Splunk all
    - splunk/restart_sshd #Splunk all
    - splunk/configure_iptables #Splunk all
    - splunk/change_hostname #Splunk all
    - splunk/adjust_ulimits #Splunk all
    - splunk/copy_splunk_rpm #Splunk all
    - splunk/install_rpm #Splunk all
    - splunk/initial_start #Splunk all
    
- name: Configure Splunk manager
  hosts: Splunk_Manager
  vars_files: 
  - /ansible/group_vars/all.yml
  - /ansible/deployment_vars.yml
  roles:
    - splunk/configure_clustermanager #Splunk CM1
    - splunk/configure_clustermanager_settings #Splunk CM1
    - splunk/configure_addons_manager #Splunk CM1
    - splunk/configure_addons_cluster #Splunk CM1
    - splunk/configure_indexes #Splunk CM1
    - splunk/configure_tls #Splunk CM1

- name: Configure Splunk Search
  hosts: Splunk_ES
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles:
    - splunk/configure_searchhead #Splunk SH1
    - splunk/configure_searchhead_settings #Splunk SH1
    - splunk/configure_addons_search #Splunk SH1
    - splunk/configure_indexes #Splunk SH1
    - splunk/configure_tls #Splunk SH1

- name: Configure Splunk Forward
  hosts: Splunk_Forward
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles:
    - splunk/configure_forward #Splunk FWD
    - splunk/configure_forward_settings #Splunk FWD
    - splunk/configure_tls #Splunk FWD

- name: Configure Splunk Peers
  hosts: Splunk_Indexers
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles:
    - splunk/configure_indexer #Splunk Peer
    - splunk/configure_peer_settings #Splunk Peer
    - splunk/configure_tls #Splunk Peer

- name: Configure Splunk Virtual machines
  hosts: Splunk
  ignore_errors: true
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles:
    - splunk/wrap-up #Splunk all

- name: Change splunk fwd to DMZ
  hosts: localhost
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  vars:
    - vm_name: "{{Splunk_Forward.Name}}"
    - adapter_label: "Network adapter 1"
    - portgroup: "Host Data Collection"
  roles:
    - vmware/vcenter/change_portgroups #Splunk FWD
    - vmware/vcenter/restart_vm #Splunk FWD

- name: Configure SecurityOnion Manager
  hosts: SO_MGR
  gather_facts: False
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles:
    - seconion/test_connectivity #SecurityOnion ManagerSearch
    - seconion/create_licensefile #SecurityOnion ManagerSearch
    - seconion/configure_networking #SecurityOnion ManagerSearch
    - seconion/install_so_manager #SecurityOnion ManagerSearch