---
- name: generate variables for deployment
  hosts: localhost
  gather_facts: true
  connection: local
  become: true
  vars:
    - file_source: "network-gateway.yaml"
  vars_files: 
    - ./deployment_vars.yml
    - /ansible/deployment_vars.yml
  roles:
    - generate/host_vm_address #Required for deployment DO NOT REMOVE
    - generate/tftp_server #Required for deployment DO NOT REMOVE
    - generate/dhcp_server #Required for deployment DO NOT REMOVE
    - generate/network_configs #Required for deployment DO NOT REMOVE
    - seconion/iso  #SecurityOnion ManagerSearch

- name: install system and virtual machines
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles: 
    - seconion/upload_iso  #SecurityOnion
    - seconion/deploy_manager_vm  #SecurityOnion

- name: Configure SecurityOnion Manager
  hosts: SO_MGR
  gather_facts: False
  vars_files: 
    - /ansible/group_vars/all.yml
    - /ansible/deployment_vars.yml
  roles:
    - seconion/test_connectivity #SecurityOnion ManagerSearch
    - seconion/create_licensefile #SecurityOnion ManagerSearch
    - seconion/configure_networking #SecurityOnion ManagerSearch
    - seconion/install_so_manager #SecurityOnion ManagerSearch
