---
- name: generate variables for deployment
  hosts: localhost
  gather_facts: true
  connection: local
  become: true
  ignore_errors: true
  vars:
    - file_source: "network-eight.yaml"
  vars_files: 
    - ./deployment_vars.yml
    - /ansible/deployment_vars.yml
  roles:
    - generate/host_vm_address #Required for deployment DO NOT REMOVE
    - seconion/packages #SecurityOnion Sensors
    - seconion/make_answers  #SecurityOnion Sensors
    - pxe/centos

- name: configure sensors
  hosts: Sensors
  gather_facts: true
  become: true
  vars_files: 
    - ./deployment_vars.yml
    - /ansible/deployment_vars.yml
  roles:
    - centos/install_packages
    - centos/get_so_package
    - seconion/create_licensefile #SecurityOnion Sensors
    - seconion/get_answers #SecurityOnion Sensors
    - seconion/install_so_sensor #SecurityOnion Sensors
