#Local Machine Username
localhost_username: admin

#Local Machine Password
localhost_password: password

#username for IPMI interface
IPMI_Username: admin

#What is the IPMI Password?
IPMI_Pass: password

#What is the password going to be for this DMSS Kit?
DMSS_Pass: password

#What are the first 3 octets?(10.1.0) 
octet: "192.168.86"

#Enter your domain
domain: test

#number of Servers; max is 3
Nodes: 3

#number of Sensors; max is 6
Sensors: 6

##############################################################################################
#Constant Variables: edit with caution
#General vars#################################################################################

#SecurityOnion Vars##############################
onionIso: "securityonion-2.3.250-20230519.iso"
centos7Iso: "CentOS-7-x86_64-DVD-2009.iso"
so_install_dir: "/tmp/"
so_default_user: xadministrator
so_soc_user: xadministrator@onion.com #SecurityOnion SOC user. No capital letters or deployment will fail
so_install_type: MANAGERSEARCH #options are MANAGER OR MANAGERSEARCH for manager vm

#System Settings#################################
Max_Nodes: 3 #any change to a value greater than 3 will require adjustments to the roles/generate/varaibles/templates/secrets.yml file
Max_Sensors: 6 #any change to a value greater than 6 will require adjustments to the roles/generate/varaibles/templates/secrets.yml file
node_ip_range: "30-32" #this is only the scan range, it does not reflect the node ips in the /ansible/group_vars/all.yml file
sensor_ip_range: "33-38" #this is only the scan range, it does not reflect the sensor ips in the /ansible/group_vars/all.yml file
