---
- name: install rpms
  shell: |
    sudo rpm -Uvh --nodeps /nsm/repo/{{item}}*.rpm
  loop:
    - GeoIP
    - MySQL-python
    - NetworkManager
    - NetworkManager-libnm
    - NetworkManager-team
    - NetworkManager-tui
    - NetworkManager-wifi
    - OpenIPMI
    - OpenIPMI-libs
    - OpenIPMI-modalias
    - acl
    - aic94xx-firmware
    - alsa-firmware
    - alsa-lib
    - alsa-tools-firmware
    - apr
    - apr-util
    - argon2
    - audit
    - audit-libs
    - audit-libs-python
    - authconfig
    - basesystem
    - bash
    - bc
    - bind-export-libs
    - bind-libs
    - bind-libs-lite
    - bind-license
    - bind-utils
    - binutils
    - biosdevname
    - btrfs-progs
    - bzip2-libs
    - c-ares
    - ca-certificates
    - centos-logos
    - centos-release
    - checkpolicy
    - chkconfig
    - chrony
    - container-selinux
    - containerd
    - coreutils
    - cpio
    - cracklib
    - cracklib-dicts
    - createrepo
    - cronie
    - cronie-anacron
    - crontabs
    - cryptsetup-libs
    - curl
    - cyrus-sasl-lib
    - dbus
    - dbus-glib
    - dbus-libs
    - dbus-python
    - deltarpm
    - device-mapper
    - device-mapper-event
    - device-mapper-event-libs
    - device-mapper-libs
    - device-mapper-persistent-data
    - dhclient
    - dhcp-common
    - dhcp-libs
    - diffutils
    - dmidecode
    - docker-ce
    - docker-ce-cli
    - docker-ce-rootless-extras
    - dracut
    - dracut-config-rescue
    - dracut-network
    - e2fsprogs
    - e2fsprogs-libs
    - ebtables
    - elfutils-default-yama-scope
    - elfutils-libelf
    - elfutils-libs
    - ethtool
    - expat
    - file
    - file-libs
    - filesystem
    - findutils
    - fipscheck
    - fipscheck-lib
    - firewalld
    - firewalld-filesystem
    - freetype
    - fuse
    - fuse-libs
    - fuse-overlayfs
    - fuse3-libs
    - fxload
    - gawk
    - gdbm
    - geoipupdate
    - gettext
    - gettext-libs
    - git
    - glib2
    - glibc
    - glibc-common
    - gmp
    - gnupg2
    - gnutls
    - gobject-introspection
    - gpgme
    - gpm-libs
    - grep
    - groff-base
    - grub2
    - grub2-common
    - grub2-pc
    - grub2-pc-modules
    - grub2-tools
    - grub2-tools-extra
    - grub2-tools-minimal
    - grubby
    - gzip
    - hardlink
    - hostname
    - httpd-tools
    - hwdata
    - info
    - initscripts
    - ipmitool
    - iproute
    - iprutils
    - ipset
    - ipset-libs
    - iptables
    - iputils
    - irqbalance
    - ivtv-firmware
    - iwl100-firmware
    - iwl1000-firmware
    - iwl105-firmware
    - iwl135-firmware
    - iwl2000-firmware
    - iwl2030-firmware
    - iwl3160-firmware
    - iwl3945-firmware
    - iwl4965-firmware
    - iwl5000-firmware
    - iwl5150-firmware
    - iwl6000-firmware
    - iwl6000g2a-firmware
    - iwl6000g2b-firmware
    - iwl6050-firmware
    - iwl7260-firmware
    - jansson
    - jq
    - json-c
    - kbd
    - kbd-legacy
    - kbd-misc
    - kernel
    - kernel-tools
    - kernel-tools-libs
    - kexec-tools
    - keyutils-libs
    - keyutils-libs-devel
    - kmod
    - kmod-libs
    - kpartx
    - krb5-devel
    - krb5-libs
    - less
    - libacl
    - libaio
    - libargon2
    - libassuan
    - libattr
    - libblkid
    - libcap
    - libcap-ng
    - libcgroup
    - libcom_err
    - libcom_err-devel
    - libcroco
    - libcurl
    - libdaemon
    - libdb
    - libdb-utils
    - libdrm
    - libedit
    - libestr
    - libfastjson
    - libffi
    - libgcc
    - libgcrypt
    - libgomp
    - libgpg-error
    - libidn
    - libkadm5
    - libmnl
    - libmount
    - libmspack
    - libndp
    - libnetfilter_conntrack
    - libnfnetlink
    - libnl3
    - libnl3-cli
    - libpcap
    - libpciaccess
    - libpipeline
    - libpng
    - libpwquality
    - libreport-filesystem
    - libseccomp
    - libselinux
    - libselinux-devel
    - libselinux-python
    - libselinux-utils
    - libsemanage
    - libsemanage-python
    - libsepol
    - libsepol-devel
    - libsmartcols
    - libsmi
    - libsodium
    - libss
    - libssh2
    - libstdc++
    - libsysfs
    - libtasn1
    - libteam
    - libtirpc
    - libtool-ltdl
    - libunistring
    - libuser
    - libutempter
    - libuuid
    - libverto
    - libverto-devel
    - libxml2
    - libxml2-python
    - libxslt
    - libyaml
    - linux-firmware
    - logrotate
    - lsscsi
    - lua
    - lvm2
    - lvm2-libs
    - lz4
    - lzo
    - make
    - man-db
    - mariadb-devel
    - mariadb-libs
    - mdadm
    - microcode_ctl
    - mozjs17
    - ncurses
    - ncurses-base
    - ncurses-libs
    - net-snmp-libs
    - net-tools
    - nettle
    - newt
    - newt-python
    - nmap-ncat
    - nspr
    - nss
    - nss-pem
    - nss-softokn
    - nss-softokn-freebl
    - nss-sysinit
    - nss-tools
    - nss-util
    - ntpdate
    - numactl-libs
    - oniguruma
    - open-vm-tools
    - openldap
    - openpgm
    - openssh
    - openssh-clients
    - openssh-server
    - openssl
    - openssl-devel
    - openssl-libs
    - os-prober
    - p11-kit
    - p11-kit-trust
    - pam
    - parted
    - passwd
    - patch
    - pciutils
    - pciutils-libs
    - pcre
    - pcre-devel
    - perl
    - perl-Carp
    - perl-Encode
    - perl-Error
    - perl-Exporter
    - perl-File-Path
    - perl-File-Temp
    - perl-Filter
    - perl-Getopt-Long
    - perl-Git
    - perl-HTTP-Tiny
    - perl-PathTools
    - perl-Pod-Escapes
    - perl-Pod-Perldoc
    - perl-Pod-Simple
    - perl-Pod-Usage
    - perl-Scalar-List-Utils
    - perl-Socket
    - perl-Storable
    - perl-TermReadKey
    - perl-Text-ParseWords
    - perl-Time-HiRes
    - perl-Time-Local
    - perl-constant
    - perl-libs
    - perl-macros
    - perl-parent
    - perl-podlators
    - perl-threads
    - perl-threads-shared
    - pinentry
    - pkgconfig
    - plymouth
    - plymouth-core-libs
    - plymouth-scripts
    - policycoreutils
    - policycoreutils-python
    - polkit
    - polkit-pkla-compat
    - popt
    - postfix
    - procps-ng
    - pth
    - pygpgme
    - pyliblzma
    - python
    - python-IPy
    - python-chardet
    - python-configobj
    - python-decorator
    - python-deltarpm
    - python-firewall
    - python-gobject-base
    - python-iniparse
    - python-kitchen
    - python-libs
    - python-linux-procfs
    - python-perf
    - python-pycurl
    - python-pyudev
    - python-schedutils
    - python-slip
    - python-slip-dbus
    - python-urlgrabber
    - python3
    - python3-libs
    - python3-pip
    - python3-setuptools
    - python36-PyYAML
    - python36-certifi
    - python36-chardet
    - python36-contextvars
    - python36-dateutil
    - python36-distro
    - python36-docker
    - python36-docker-pycreds
    - python36-idna
    - python36-immutables
    - python36-jinja2
    - python36-lxml
    - python36-m2crypto
    - python36-markupsafe
    - python36-msgpack
    - python36-mysql
    - python36-packaging
    - python36-psutil
    - python36-pycurl
    - python36-pyparsing
    - python36-pysocks
    - python36-pytz
    - python36-requests
    - python36-rpm
    - python36-six
    - python36-urllib3
    - python36-websocket-client
    - python36-zmq
    - pyxattr
    - qrencode-libs
    - readline
    - rootfiles
    - rpm
    - rpm-build-libs
    - rpm-libs
    - rpm-python
    - rsync
    - rsyslog
    - salt
    - salt-master
    - salt-minion
    - sed
    - selinux-policy
    - selinux-policy-targeted
    - setools-libs
    - setup
    - shadow-utils
    - shared-mime-info
    - slang
    - slirp4netns
    - snappy
    - sqlite
    - sshpass
    - sudo
    - systemd
    - systemd-libs
    - systemd-python
    - systemd-sysv
    - sysvinit-tools
    - tar
    - tcp_wrappers-libs
    - tcpdump
    - teamd
    - trousers
    - tuned
    - tzdata
    - unzip
    - ustr
    - util-linux
    - vim-common
    - vim-enhanced
    - vim-filesystem
    - vim-minimal
    - virt-what
    - wazuh-agent
    - wget
    - which
    - wireshark
    - wpa_supplicant
    - xfsprogs
    - xmlsec1
    - xmlsec1-openssl
    - xz
    - xz-libs
    - yum
    - yum-metadata-parser
    - yum-plugin-fastestmirror
    - yum-plugin-versionlock
    - yum-utils
    - zeromq
    - zlib
    - zlib-devel

