---
- name: compress splunk apps
  archive:
    path: "/ansible/files/splunk/apps/{{item}}/"
    dest: "/var/www/html/repo/{{item}}_apps.tar.gz"
  loop:
    - Manager
    - cluster
    - Search
    - Indexer
    - Heavy
  become: true

- name: copy tar to web
  copy:
    src: "{{splunk_dir}}{{splunk_file}}"
    dest: /var/www/html/repo/
  become: True
...