---
- name: copy kickstart to so dir
  template:
    src: "./sensor.cfg"
    dest: "/opt/baremetal/seconion/ks.cfg"
  become: true

- name: chmod the sys
  shell: |
    sudo chmod +x -R /opt/baremetal/seconion/
  become: true

- name: compile Security Onion "{{item.Name}}"
  shell: |
    cd /opt/baremetal/seconion/
    sudo mkisofs -o "/ansible/files/seconion/{{item.Name}}.iso" -allow-limited-size -b isolinux/isolinux.bin -J -R -l -c isolinux/boot.cat --no-emul-boot  --boot-load-size 4 --boot-info-table --eltorito-alt-boot -e images/efiboot.img -no-emul-boot -graft-points -joliet-long -R -V "CentOS 7 x86_64" .
  become: true

- name: convert to uefi
  shell: |
    sudo chmod 777 "/ansible/files/seconion/{{item.Name}}.iso"
    sudo isohybrid --uefi "/ansible/files/seconion/{{item.Name}}.iso"
  become: true
  
- name: template smc
  template:
    src: ./smc
    dest: /ansible/files/smc

- name: mount esxi images
  shell: |
    "cat /ansible/files/smc | sudo /ansible/SMCIPMITool/SMCIPMITool {{ item.IP }} {{ IPMI_Username }} '{{ IPMI_Pass }}' shell"
  delegate_to: localhost

- name: Pause for two minutes while ESXi hosts are rebooted after firstboot
  pause:
    seconds: 120

...