---
- name: copy kickstart to so dir
  template:
    src: "./{{ item }}.cfg"
    dest: "/opt/baremetal/seconion/ks.cfg"
  become: true

- name: manager automation
  template:
    src: "./distributed-airgap-{{item}}"
    dest: "/opt/baremetal/seconion/SecurityOnion/setup/automation/distributed-airgap-manager"
  become: true

- name: chmod the sys
  shell: |
    sudo chmod +x -R /opt/baremetal/seconion/
  become: true


- name: compile Security Onion "{{item}}"
  shell: |
    cd /opt/baremetal/seconion/
    sudo mkisofs -o "/ansible/files/seconion/{{item}}.iso" -allow-limited-size -b isolinux.bin -J -R -l -c boot.cat --no-emul-boot  --boot-load-size 4 --boot-info-table --eltorito-alt-boot -e images/efiboot.img -no-emul-boot -graft-points -joliet-long -R -V "CentOS 7 x86_64" .
  become: true

- name: convert to uefi
  shell: |
    sudo chmod 777 "/ansible/files/seconion/{{item}}.iso"
    sudo isohybrid --uefi "/ansible/files/seconion/{{item}}.iso"
  become: true
    

...