---
# - name: Fix is_airgap variable for unattended offline install on SO 2.3.140
#   lineinfile:
#     path: "/home/xadministrator/SecurityOnion/setup/so-setup"
#     insertafter: '^automation\=\$2'
#     line: 'is_airgap=true'
#   become: True

# - name: Fix is_iso variable for unattended offline install on SO 2.3.140
#   lineinfile:
#     path: "/home/xadministrator/SecurityOnion/setup/so-setup"
#     insertafter: 'Network is up on'
#     line: 'is_iso=false'
#   become: True

# - name: copy sbin to dir
#   copy:
#     src: /home/{{so_default_user}}/SecurityOnion/salt/common/sbin
#     dest: /usr/
#     owner: root
#     group: root
#     mode: 0777
#   become: true

- name: Change permissions on Security Onion Bash Scripts
  shell: "cd /home/{{so_default_user}}/SecurityOnion && find . -name *.sh | while read line; do chmod 754 $line ;done"
  become: true

- name: Run Security Onion Managernode Setup
  shell: |
    cd /home/{{so_default_user}}/SecurityOnion/setup/automation/
    sudo /home/{{so_default_user}}/SecurityOnion/setup/so-setup network distributed-airgap-manager
  become: true
  become_method: sudo
  ignore_errors: True
