---
#Splunk Vars ########################################################################################################################################
indexgenkey: "{{ indexpasskey }}"
genkey: "{{ passkey }}"
encryptedpassword: "{{encryptedPass}}"

#Server Vars#########################################################################################################################################
ntp: "{{ octet}}.1"

CP1:
  Name: CP1
  IP: "{{ octet }}.30"
  Subnet: "255.255.255.192"
  datastore: "CP1_VMStore"
  smc: "/ansible/files/smc1"
  server:
    Hostname: "CP1"
    IP: "{{ octet }}.11"
    Subnet: "255.255.255.192"
    Gateway: "{{ octet }}.1"
    mgmt_nic: "vmnic0" #Must be VMNIC0 or else PXE will fail due to 8 port switch
    iso_path: "/ansible/files/esxi/CP1.iso"
    vmotion: "{{ octet }}.242"
    License: "{{license[0]}}"
  

CP2:
  Name: CP2
  IP: "{{ octet }}.31"
  Subnet: "255.255.255.192"
  datastore: "CP2_VMStore"
  smc: "/ansible/files/smc2"
  server:
    Hostname: "CP2"
    IP: "{{ octet }}.12"
    Subnet: "255.255.255.192"
    Gateway: "{{ octet }}.1"
    mgmt_nic: "vmnic0" #Must be VMNIC0 or else PXE will fail due to 8 port switch
    iso_path: "/ansible/files/esxi/CP2.iso"
    vmotion: "{{ octet }}.243"
    License:  "{{license[1]}}"

CP3:
  Name: CP3
  IP: "{{ octet }}.32"
  Subnet: "255.255.255.192"
  datastore: "CP3_VMStore"
  smc: "/ansible/files/smc3"
  server:
    Hostname: "CP3"
    IP: "{{ octet }}.13"
    Subnet: "255.255.255.192"
    Gateway: "{{ octet }}.1"
    mgmt_nic: "vmnic0" #Must be VMNIC0 or else PXE will fail due to 8 port switch
    iso_path: "/ansible/files/esxi/CP3.iso"
    vmotion: "{{ octet }}.244"
    License: "{{license[2]}}"

MR0:
  Name: MR0
  IP: "{{ octet }}.33"
  Subnet: "255.255.255.192"
  os_drives:
    - "sda"
  data_drives:
    - "sdb"
    - "sdc"
    - "sdd"
  server:
    Name: "SOSensor0"
    IP: "{{ octet }}.211"
    Subnet: "255.255.255.240"
    Gateway: "{{ octet }}.209"
    Prefix: "28"
    mgmt_nic: "eno1"
    monitor_nic:
      - "eno2"
      - "eno3"
      - "eno4"
    Username: "{{so_default_user}}"
    iso_path: "/ansible/files/so/SOsensor1.iso"
    smc: "/ansible/files/smc5"


MR1:
  Name: MR1
  IP: "{{ octet }}.34"
  Subnet: "255.255.255.192"
  os_drives:
    - "sda"
  data_drives:
    - "sdb"
    - "sdc"
    - "sdd"
  server:
    Name: "SOSensor1"
    IP: "{{ octet }}.212"
    Subnet: "255.255.255.240"
    Gateway: "{{ octet }}.209"
    Prefix: "28"
    mgmt_nic: "eno1"
    monitor_nic:
      - "eno2"
      - "eno3"
      - "eno4"
    Username: "{{so_default_user}}"
    iso_path: "/ansible/files/so/SOsensor2.iso"
    smc: "/ansible/files/smc6"

MR2:
  Name: MR2
  IP:  "{{ octet }}.35"
  Subnet: "255.255.255.192"
  os_drives:
    - "sda"
  data_drives:
    - "sdb"
    - "sdc"
    - "sdd"
  server:
    Name: "SOSensor2"
    IP: "{{ octet }}.213"
    Subnet: "255.255.255.240"
    Gateway: "{{ octet }}.209"
    Prefix: "28"
    mgmt_nic: "eno1"
    monitor_nic:
      - "eno2"
      - "eno3"
      - "eno4"
    Username: "{{so_default_user}}"
    iso_path: "/ansible/files/so/SOsensor3.iso"
    smc: "/ansible/files/smc7"

MR3:
  Name: MR3
  IP: "{{ octet }}.36"
  Subnet: "255.255.255.192"
  os_drives:
    - "sda"
  data_drives:
    - "sdb"
    - "sdc"
    - "sdd"
  server:
    Name: "SOSensor3"
    IP: "{{ octet }}.214"
    Subnet: "255.255.255.240"
    Gateway: "{{ octet }}.209"
    Prefix: "28"
    mgmt_nic: "eno1"
    monitor_nic:
      - "eno2"
      - "eno3"
      - "eno4"
    Username: "{{so_default_user}}"
    iso_path: "/ansible/files/so/SOsensor4.iso"
    smc: "/ansible/files/smc8"

MR4:
  Name: MR4
  IP: "{{ octet }}.37"
  Subnet: "255.255.255.192"
  os_drives:
    - "sda"
  data_drives:
    - "sdb"
    - "sdc"
    - "sdd"
  server:
    Name: "SOSensor4"
    IP: "{{ octet }}.215"
    Subnet: "255.255.255.240"
    Gateway: "{{ octet }}.209"
    Prefix: "28"
    Username: "{{so_default_user}}"
    mgmt_nic: "eno1"
    monitor_nic:
      - "eno2"
      - "eno3"
      - "eno4"
    iso_path: "/ansible/files/so/SOsensor5.iso"
    smc: "/ansible/files/smc9"

MR5:
  Name: MR5
  IP: "{{ octet }}.38"
  Subnet: "255.255.255.192"
  os_drives:
    - "sda"
  data_drives:
    - "sdb"
    - "sdc"
    - "sdd"
  server:
    Name: "SOSensor5"
    IP: "{{ octet }}.216"
    Subnet: "255.255.255.240"
    Gateway: "{{ octet }}.209"
    Prefix: "28"
    mgmt_nic: "eno1"
    monitor_nic:
      - "eno2"
      - "eno3"
      - "eno4"
    Username: "{{so_default_user}}"
    iso_path: "/ansible/files/so/sensor6.iso"
    smc: "/ansible/files/smc10"


#VM Vars#########################################################################################################################################
VCSA:
  Name: "VCSA-01"
  IP: "{{ octet }}.10"
  Prefix: "26"
  Gateway: "{{ octet }}.1"
  Subnet: "255.255.255.192"
  Interface_1: "{{ vlan2 }}"
  Username: 'administrator@{{ TeamKitNum }}.mil'
  esxi_infrastructure_fqdn: "{{ octet }}.5"
  Hostname: 'VCSA-01'
  domain: '{{TeamKitNum}}.mil'
  searchpath: ""
  size: 'small'
  ova_file: 'VMware-vCenter-Server-Appliance-7.0.3.01300-21290409_OVF10.ova'
  datastore: 'CP2_VMStore'
  filestore: 'datastore1'
  network: 'VM Network'
  datacenter_name: '{{TeamKitNum}}'
  vm_folder: '{{TeamKitNum}}_VMS'
  License: "{{ vcenter_license }}"
  Deploy_loc: "{{octet}}.12"

 
PA:
  Name: "PaloAlto"
  IP: "{{ octet }}.2"
  Subnet: "255.255.255.192"
  Interface0: "Management"
  Interface1: "Management"
  Interface2: "Domain Services"
  Interface3: "Data Analysis"
  Interface4: "Host Interrogation"
  Interface5: "Host Data Collection"
  Interface6: "Network Data Collection"
  Interface7: "VMotion"
  Interface10: "Provisioning"
  Interface9: "External"
  loc: "{{ octet }}.13"
  Storage: "100"
  Mem: "150000"
  CPU: "2"
  Username: 'admin'
  deploy_type: "ova"
  datastore: "CP3_VMStore"
  netmask: "255.255.255.192"
  Gateway: "{{ octet }}.1"

DC1:
  IP: "{{ octet }}.130"
  Subnet: "255.255.255.192"
  Interface_1: "{{ vlan10 }}"
  loc: "{{ octet }}.11"
  Storage: "80"
  Mem: "8000"
  CPU: "2"
  deploy_type: "ova"
  datastore: 'CP1_VMStore'

DC2:
  IP: "{{ octet }}.131"
  Subnet: "255.255.255.192"
  Gateway: "{{ octet }}.1"
  Interface_1: "{{ vlan10 }}"
  loc: "{{ octet }}.13"
  Storage: "80"
  Mem: "8000"
  CPU: "2"
  deploy_type: "ova"
  datastore: 'CP3_VMStore'

#Splunk VM Vars ############################################################################################################################################

Splunk_Manager:
  Name: "CM1"
  IP: "{{ octet }}.194"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.193"
  Prefix: "28"
  Interface_1: "{{ vlan20 }}"
  loc: "{{ octet }}.11"
  Storage: "500"
  Mem: "16000"
  CPU: "12"
  Username: "{{splunk_default_user}}"
  deploy_type: "ova"
  datastore: 'CP1_VMStore'

Splunk_Search:
  Name: "SH1"
  IP: "{{ octet }}.198"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.193"
  Prefix: "28"
  Interface_1: "{{ vlan20 }}"
  loc: "{{ octet }}.12"
  Storage: "500"
  Mem: "32000"
  CPU: "16"
  Username: "{{splunk_default_user}}"
  deploy_type: "ova"
  datastore: 'CP2_VMStore'

Splunk_Forward:
  Name: "Splunk_Forward"
  IP: "{{ octet }}.228"
  IP2: "{{ octet }}.199"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.225"
  Gateway2: "{{ octet }}.193"
  Prefix: "28"
  Interface_1: "{{ vlan20 }}"
  loc: "{{ octet }}.13"
  Storage: "500"
  Mem: "12000"
  CPU: "12"
  Username: "{{splunk_default_user}}"
  deploy_type: "ova"
  datastore: 'CP3_VMStore'

Splunk_Indexer:
  Name: "IDX"
  IP: "{{ octet }}.19"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.193"
  Prefix: "28"
  Interface_1: "{{ vlan20 }}"
  loc: "{{ octet }}.11"
  Storage: "10000"
  Mem: "64000"
  CPU: "18"
  Username: "{{splunk_default_user}}"
  deploy_type: "ova"

# SecurityOnion VM vars#########################################################################################################################################

SOManager: #deploying as manager/search
  Name: "SOManager"
  IP: "{{ octet }}.210"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.209"
  Prefix: "28"
  Interface_1: "{{ vlan50 }}"
  mgmt_nic: "ens192"
  loc: "{{ octet }}.13"
  Storage: "500"
  CPU: "4"
  Mem: "32000"
  esheap: "8192" # 33% of Mem
  lsheap: "4096" # No greater than 25% or 4gb
  soc: "{{ so_soc_user }}"
  Username: "{{so_default_user}}"
  deploy_type: "iso"
  iso_path: "SOManager.iso"
  datastore: 'CP2_VMStore'
  isostore: 'CP2_FileStore'

SOSearch: #Currently Not deploying
  Name: "SOSearch"
  IP: "{{ octet }}.217"
  Subnet: "255.255.255.240"
  Gateway: "{{ octet }}.209"
  Prefix: "28"
  Interface_1: "{{ vlan50 }}"
  loc: "{{ octet }}.13"
  Storage: "500"
  CPU: "8"
  Mem: "24000"
  esheap: "7920" #33% of mem
  Username: "{{so_default_user}}"
  deploy_type: "iso"
  iso_path: "SOSearch.iso"
  datastore: 'CP2_VMStore'
  isostore: 'CP2_FileStore'





#####