#!/bin/bash

# Copyright 2014-2022 Security Onion Solutions, LLC

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

TESTING=true
is_airgap=true
is_iso=false
address_type=static
ADMINUSER={{so_default_user}}
ADMINPASS1={{ DMSS_Pass }}
ADMINPASS2={{ DMSS_Pass }}
ALLOW_CIDR={{octet}}.0/26
ALLOW_ROLE=a
BASICZEEK=2
BASICSURI=2
# BLOGS=
#BNICS=eth1
ZEEKVERSION=ZEEK
# CURCLOSEDAYS=
# EVALADVANCED=BASIC
GRAFANA=1
# HELIXAPIKEY=
HNMANAGER=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
HNSENSOR=inherit
HOSTNAME=SOManager
install_type={{ so_install_type }}
INTERWEBS=AIRGAP
# LSINPUTBATCHCOUNT=
# LSINPUTTHREADS=
# LSPIPELINEBATCH=
# LSPIPELINEWORKERS=
MANAGERADV=BASIC
MDNS={{ DC1.IP }}
MGATEWAY={{ SOManager.Gateway }}
MIP={{ SOManager.IP }}
MMASK=28
MNIC=ens192
# MSEARCH=
# MSRV=
# MTU=
NIDS=Suricata
NODE_ES_HEAP_SIZE={{ SOManager.esheap }}
NODE_LS_HEAP_SIZE={{ SOManager.lsheap }}
NODESETUP=NODEBASIC
NSMSETUP=BASIC
NODEUPDATES=MANAGER
# OINKCODE=
OSQUERY=1
# PATCHSCHEDULEDAYS=
# PATCHSCHEDULEHOURS=
PATCHSCHEDULENAME=auto
PLAYBOOK=1
# REDIRECTHOST=
REDIRECTINFO=IP
RULESETUP=ETOPEN
# SHARDCOUNT=
# SKIP_REBOOT=
SOREMOTEPASS1={{ DMSS_Pass }}
SOREMOTEPASS2={{ DMSS_Pass }}
STRELKA=1
THEHIVE=0
WAZUH=0
WEBUSER={{ SOManager.soc }}
WEBPASSWD1={{ DMSS_Pass }}
WEBPASSWD2={{ DMSS_Pass }}
